[package]
name = "gicp_slam_vulkan"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"

log = "0.4.28"
env_logger = "0.11.8"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10"

pcd-rs = { version = "0.12.0", features = ["derive"] }

nalgebra = "0.34.1"

vulkano = "0.35.0"
vulkano-shaders = { version = "0.34.0" }
bytemuck = "1.25.0"

rayon = "1.12.0"