version: '3.8'

services:
  slam-vulkan:
    build: .
    container_name: gicp_slam_container
    tty: true
    stdin_open: true
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,display
      - NVIDIA_VISIBLE_DEVICES=all
      # - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
      - RUST_BACKTRACE=1
    volumes:
      - .:/workspace
      # コンテナ内のビルドキャッシュをホストと分離（ビルドエラー防止）
      - cargo_target:/workspace/target
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, graphics]

volumes:
  cargo_target: